const aparts = [
    {
        "id": 7000901,
        "adres": "Warsaw, Mokotow",
        "price": 1075,
        "currency": "USD",
        "details": "2-room apartment with balcony",
        "size": 52,
        "added": "2025-03-27",
        "saved": 0,
        "status": "available",
        "image": ['https://medialibrarycfo.entrata.com/fit-in/700x700/15077/MLv3/3/27/2022/07/27/124402/62e18772519326.42629581743.jpg', 'https://i.digsdigs.com/2013/07/45-cozy-rustic-bedroom-design-ideas-8.jpg', 'https://u.profitroom.pl/2019-marinaapartments-pl/thumb/1920x1080/uploads/vlcsnap-2020-02-06-11h50m25s133.jpg'],
        "category": "living"
    },
    {
        "id": 7000902,
        "adres": "Kyiv, Obolon",
        "price": 930,
        "currency": "EUR",
        "details": "250 sq.m. office space",
        "size": 250,
        "added": "2025-02-02",
        "saved": 1,
        "status": "available",
        "image": ['https://www.rentfurniture.com/office/img/axton.jpg', 'https://maisonoffice.vn/en/wp-content/uploads/2024/03/modern-office-1.jpg', 'https://www.pressglass.com/wp-content/uploads/2024/02/MicrosoftTeams-image-20-2-1030x687.jpeg'],
        "category": "business"
    },
    {
        "id": 7000903,
        "adres": "Warsaw, Center",
        "price": 3220,
        "currency": "USD",
        "details": "Fitness club in city center",
        "size": 430,
        "added": "2025-01-31",
        "saved": 1,
        "status": "available",
        "image": ["https://top-gym.pl//wp-content/uploads/2020/10/2bbe19b224b5aea85c79cb61fbcc30be.jpg", 'https://justgym.pl/wp-content/uploads/2021/08/JustGYM_Katowice_otwarcie_9-scaled.jpg', 'https://justgym.pl/wp-content/uploads/2021/07/Lodz_piotrkowska_gotowe_8-768x503.jpg', 'https://justgym.pl/wp-content/uploads/2021/07/justGYM_8_male-768x503.jpg'],
        "category": "business"
    },
    {
        "id": 7000904,
        "adres": "London, Soho",
        "price": 715,
        "currency": "EUR",
        "details": "1-room apartment",
        "size": 38,
        "added": "2025-01-29",
        "saved": 0,
        "status": "available",
        "image": ['https://images1.apartments.com/i2/rpFjUhcei-XpnXE02TOyU3BLtqw0Dwy8kEyD61HJltM/117/image.jpg', 'https://www.decorilla.com/online-decorating/wp-content/uploads/2020/07/Modern-apartment-decor-for-a-rustic-studio-unit.jpg'],
        "category": "living"
    },
    {
        "id": 7000905,
        "adres": "Warsaw, Ursynow",
        "price": 975,
        "currency": "USD",
        "details": "2-room apartment (open kitchen)",
        "size": 52,
        "added": "2025-02-02",
        "saved": 0,
        "status": "available",
        "image": ['https://www.astraapartments.com.au/wp-content/uploads/2024/05/Astra-Apartments-Sydney-CBD-2-bed-r-es-living-520x320.jpg', 'https://i.pinimg.com/736x/17/f5/65/17f5653a1457ba77285cbcb4789db69b.jpg', 'https://www.home-designing.com/wp-content/uploads/2014/06/one-bedroom-house-plan.jpg'],
        "category": "living"
    },
    {
        "id": 7000906,
        "adres": "Warsaw, Mokotow",
        "price": 1615,
        "currency": "EUR",
        "details": "3-room PREMIUM apartment",
        "size": 73,
        "added": "2025-01-31",
        "saved": 0,
        "status": "available",
        "image": ['https://u.profitroom.pl/2019-marinaapartments-pl/thumb/1920x1080/uploads/vlcsnap-2020-02-06-11h50m25s133.jpg', 'https://wpmedia.roomsketcher.com/content/uploads/2021/12/07133333/RoomSketcher-High-Quality-3D-Floor-Plans.jpg', 'https://www.decorilla.com/online-decorating/wp-content/uploads/2020/07/Modern-apartment-decor-for-a-masculine-bachelor-pad.jpg'],
        "category": "living"
    },
    {
        "id": 7000907,
        "adres": "Kyiv, Podil",
        "price": 1075,
        "currency": "USD",
        "details": "220 sq.m. office space",
        "size": 220,
        "added": "2025-03-02",
        "saved": 1,
        "status": "reserved",
        "image": ["https://www.constructionweekonline.in/cloud/2022/01/10/4-office.jpg"],
        "category": "business"
    },
    {
        "id": 7000908,
        "adres": "London, Westminster",
        "price": 2410,
        "currency": "EUR",
        "details": "Ready fashion store, 115 sq.m.",
        "size": 115,
        "added": "2025-04-06",
        "saved": 1,
        "status": "available",
        "image": ["https://pliki.propertydesign.pl/i/12/48/95/124895_r0_1140.jpg", 'https://www.therugmaker.com.sg/wp-content/uploads/2021/11/Rugmaker_Blog-Piece-SideImages_luxury-and-fashionable-brand-new-interior-of-cloth-store.jpg'],
        "category": "business"
    },
    {
        "id": 7000909,
        "adres": "Warsaw, Mokotow",
        "price": 1075,
        "currency": "EUR",
        "details": "3-room apartment with huge open kitchen",
        "size": 74,
        "added": "2025-04-18",
        "saved": 0,
        "status": "available",
        "image": ['https://www.home-designing.com/wp-content/uploads/2014/06/Apartment-house-plan-for-Young-Professional.jpg', 'https://www.decorilla.com/online-decorating/wp-content/uploads/2020/07/Cozy-mid-century-modern-apartment-design-with-contemporay-lighting-for-a-living-and-dining-room-by-Tatiana-nicol.jpg'],
        "category": "living"
    },
    {
        "id": 7000910,
        "adres": "Warsaw, Center",
        "price": 1305,
        "currency": "USD",
        "details": "190 sq.m. office space",
        "size": 190,
        "added": "02.12.2025",
        "saved": 1,
        "status": "reserved",
        "image": ['https://mir-s3-cdn-cf.behance.net/projects/404/fa5b5f216085601.Y3JvcCwxNDAwLDEwOTUsMCw0OA.jpg'],
        "category": "business"
    },
    {
        "id": 7000911,
        "adres": "Warsaw, Ursynow",
        "price": 960,
        "currency": "EUR",
        "details": "2-room apartment (open kitchen)",
        "size": 51,
        "added": "2025-03-29",
        "saved": 0,
        "status": "available",
        "image": ['http://www.decorilla.com/online-decorating/wp-content/uploads/2020/07/Modern-apartment-design-lounge-with-a-minimal-kitchen-by-Maurizio.jpg', 'https://www.decorilla.com/online-decorating/wp-content/uploads/2023/05/Moody-contemporary-bedroom-style-by-Ibrahim-H.jpg'],
        "category": "living"
    },
    {
        "id": 7000913,
        "adres": "Warsaw, Praga PLN",
        "price": 1020,
        "currency": "EUR",
        "details": "2-room apartment with cosy kitchen",
        "size": 49,
        "added": "2025-04-13",
        "saved": 0,
        "status": "available",
        "image": ["https://polpo-apartments.pl/images/frontpageGallery/pictures/large/0/0/14.jpg", "https://www.decorilla.com/online-decorating/wp-content/uploads/2020/08/Transitional-luxury-modern-apartment-design.jpg"],
        "category": "living"
    },
    {
        "id": 7000914,
        "adres": "Kyiv, Pechersk",
        "price": 515,
        "currency": "EUR",
        "details": "1-room apartment",
        "size": 32,
        "added": "2025-04-10",
        "saved": 0,
        "status": "available",
        "image": ["https://www.decorilla.com/online-decorating/wp-content/uploads/2020/08/Modern-Apartment-Decor-.jpg"],
        "category": "living"
    },
    {
        "id": 7000915,
        "adres": "Warsaw, Ursynow",
        "price": 1900,
        "currency": "USD",
        "details": "315 sq.m. office space",
        "size": 315,
        "added": "2025-04-18",
        "saved": 0,
        "status": "available",
        "image": ['https://officebanao.com/wp-content/uploads/2023/08/Modern-Office-Design-Ideas-1024x723.jpg', 'https://framery.com/wp-content/uploads/2024/08/framery-six-meeting-room-in-contemporary-office-768x589.jpg', 'https://s3.eu-central-1.amazonaws.com/pressland-cms/cache/article_show_cover/2x/global-humanview.jpeg'],
        "category": "business"
    },
    {
        "id": 7000916,
        "adres": "London, Center",
        "price": 1200,
        "currency": "USD",
        "details": "2-level apartment",
        "size": 53,
        "added": "2025-04-11",
        "saved": 1,
        "status": "available",
        "image": ['https://www.decorilla.com/online-decorating/wp-content/uploads/2020/07/Grey-and-blue-apartment-decor-ideas-for-a-loft-by-Mauriio.jpg', 'https://images.pexels.com/photos/27307397/pexels-photo-27307397/free-photo-of-a-modern-apartment-building-with-balconies-and-balconies.jpeg'],
        "category": "living"
    },
    {
        "id": 7000917,
        "adres": "Warsaw, Mokotow",
        "price": 1615,
        "currency": "EUR",
        "details": "3-room PREMIUM apartment",
        "size": 85,
        "added": "2025-04-02",
        "saved": 1,
        "status": "available",
        "image": ['https://www.home-designing.com/wp-content/uploads/2014/06/One-bedroom-with-balcony.jpg'],
        "category": "living"
    },
    {
        "id": 7000918,
        "adres": "Warsaw, Ursynow",
        "price": 975,
        "currency": "USD",
        "details": "2-room apartment (open kitchen)",
        "size": 47,
        "added": "2025-03-19",
        "saved": 0,
        "status": "reserved",
        "image": ['https://fpg.roomsketcher.com/image/level/1778/3d/Condominium-Unit-Floor-Plan-3D.jpg'],
        "category": "living"
    },
    {
        "id": 7000919,
        "adres": "Warsaw, Marysin",
        "price": 3115,
        "currency": "EUR",
        "details": "1400 sq.m. warehouse in logistic park",
        "size": 1400,
        "added": "2025-03-10",
        "saved": 0,
        "status": "available",
        "image": ["https://www.p3parks.com/imgm/YTE5NDIyfGExMDk1NTN8YTE5NDAxfGExMDQ5MjPT4LEA/-I8A1863.jpg", "https://www.elementlogic.net/content/uploads/sites/8/2024/10/for-4-main-functions-of-warehouse-1200x649-1.jpg", "https://portcitylogistics.com/wp-content/uploads/2024/06/warehouse.jpg", "https://www.eastmidlandsbusinesslink.co.uk/mag/wp-content/uploads/2024/02/AdobeStock_289332658.jpeg"],
        "category": "business"
    },
    {
        "id": 7000920,
        "adres": "Kyiv, Obolon",
        "price": 1775,
        "currency": "USD",
        "details": "220 sq.m. office space",
        "size": 220,
        "added": "2025-04-23",
        "saved": 0,
        "status": "available",
        "image": ['https://assets.artifactuprising.com/assets/campaigns/2020/Q1/02-06+Office+Decor+Blog+Post/4.jpg', "https://www.constructionweekonline.in/cloud/2022/01/10/4-office.jpg"],
        "category": "business"
    },
    {
        "id": 7000921,
        "adres": "London, Center",
        "price": 3400,
        "currency": "USD",
        "details": "Grocery store in city center",
        "size": 64,
        "added": "2025-04-02",
        "saved": 1,
        "status": "available",
        "image": ["https://assets.epicurious.com/photos/5720d8dadb3cd6fd5a7dd0fc/16:9/w_1280,c_limit/HEB---Store-Front.jpg", "https://assets.epicurious.com/photos/57eebe2eb382c3c017d3fff0/16:9/w_2560%2Cc_limit/supermarket-shelves.jpg", "https://www.driveresearch.com/wp-content/uploads/2020/04/Fruits-in-grocery-store.jpg"],
        "category": "business"
    },
    {
        "id": 7000922,
        "adres": "Warsaw, Mokotow",
        "price": 1075,
        "currency": "USD",
        "details": "2-room loft",
        "size": 54,
        "added": "2025-04-08",
        "saved": 0,
        "status": "available",
        "image": ['https://88designbox.com/upload/2015/07/20/modern-apartment-interior-design-02.jpg', 'https://88designbox.com/upload/2015/07/20/modern-apartment-interior-design-05.jpg'],
        "category": "living"
    },
    {
        "id": 7000923,
        "adres": "Warsaw, Targowek",
        "price": 2100,
        "currency": "EUR",
        "details": "280 sq.m. fitness club",
        "size": 280,
        "added": "2025-04-27",
        "saved": 0,
        "status": "available",
        "image": ["https://glosseniora.pl/wp-content/uploads/calypso_0544-1024x683.jpg", "https://glosseniora.pl/wp-content/uploads/calypso_0549-1024x683.jpg"],
        "category": "business"
    },
    {
        "id": 7000924,
        "adres": "London, Camden",
        "price": 1020,
        "currency": "USD",
        "details": "2-room apartment with cosy kitchen",
        "size": 52,
        "added": "2025-04-26",
        "saved": 0,
        "status": "reserved",
        "image": ["https://i.pinimg.com/736x/23/53/a2/2353a2955653335cfc461193c8186cc3.jpg"],
        "category": "living"
    },
    {
        "id": 7000925,
        "adres": "Warsaw, Center",
        "price": 1115,
        "currency": "EUR",
        "details": "1-room PREMIUM apartment",
        "size": 36,
        "added": "2025-04-19",
        "saved": 1,
        "status": "available",
        "image": ['https://plndesign.pl/wp-content/uploads/2019/11/Zlota-44-ekologiczne-dzielo-architektury-projekt-Daniel-Libeskind-plndesign-14.jpg', 'https://fancyhouse-design.com/wp-content/uploads/2023/11/Embracing-modernity-the-living-space-showcases-an-integrated-TV-unit-beside-a-cozy-L-shaped-sofa..jpg'],
        "category": "living"
    },
    {
        "id": 7000926,
        "adres": "Kyiv, Center",
        "price": 3975,
        "currency": "USD",
        "details": "Modern auto service (450 sq.m.)",
        "size": 450,
        "added": "2025-04-16",
        "saved": 1,
        "status": "available",
        "image": ["https://luxsto.com.ua/wp-content/uploads/2024/05/AF1QipPFjcuW0OR-uqByypOj14EpiIJeIKnGl7TlhffPw800-h500-k-no.jpeg", "https://sklep.skoda.pl/_next/image?url=https%3A%2F%2Fakcesoria-vgp.pl%2Fupload%2Fproduct%2F9c1676f1-8fc6-4eb4-9fa5-11c8d981bcb0%2Fprofile_img%2F22bc3efc-629b-41fc-ba41-ec07949efdf6-stavebnice-service-station-3.jpg&w=3840&q=75", "https://blog.friday-ad.co.uk/wp-content/uploads/2017/12/photo-1570071677470-c04398af73ca-912x675.jpeg"],
        "category": "business"
    },
    {
        "id": 7000927,
        "adres": "London, Newham",
        "price": 1615,
        "currency": "EUR",
        "details": "2-room modern apartment",
        "size": 92,
        "added": "2025-04-27",
        "saved": 0,
        "status": "available",
        "image": ['https://www.home-designing.com/wp-content/uploads/2014/06/Colorful-1-bedroom-apartment.jpg'],
        "category": "living"
    },
    {
        "id": 7000928,
        "adres": "Warsaw, Ursus",
        "price": 1775,
        "currency": "USD",
        "details": "220 sq.m. office space",
        "size": 220,
        "added": "2025-04-06",
        "saved": 0,
        "status": "available",
        "image": ['https://static.dezeen.com/uploads/2016/11/norm-architects-kinfolk-magazine-minimalist-offices-roundup_dezeen_2364_ss_1-852x609.jpg', 'https://officebanao.com/wp-content/uploads/2024/07/office-interior-visualization-3d-illustration-cg-render.jpg'],
        "category": "business"
    },
    {
        "id": 7000929,
        "adres": "Warsaw, Praga PLN",
        "price": 2410,
        "currency": "EUR",
        "details": "Ready fashion store",
        "size": 205,
        "added": "2025-02-10",
        "saved": 0,
        "status": "available",
        "image": ['https://ixtenso.com/media/story_section_image/8550/image-01-joe-fresh-flagship-store-interior-design-shopdesign.jpg', 'https://retaildesignblog.net/wp-content/uploads/2016/04/Atelier-New-Regime-store-Montreal-Canada.jpg', 'https://retaildesignblog.net/wp-content/uploads/2018/07/Louis-Vuitton-pop-up-store-Tokyo-Japan-02.jpg'],
        "category": "business"
    },
    {
        "id": 7000930,
        "adres": "Warsaw, Mokotow",
        "price": 1075,
        "currency": "EUR",
        "details": "2-room apartment with balcony",
        "size": 57,
        "added": "2025-03-11",
        "saved": 0,
        "status": "reserved",
        "image": ["https://decoholic.org/wp-content/uploads/2020/04/London-apartment-interior-2-720x399.jpeg"],
        "category": "living"
    },
    {
        "id": 7000931,
        "adres": "London, Lewisham",
        "price": 4300,
        "currency": "USD",
        "details": "Petrol Station",
        "size": 350,
        "added": "2025-04-13",
        "saved": 0,
        "status": "available",
        "image": ["https://lumiteam.eu/wp-content/uploads/2021/05/lotos-09.jpg", "https://lumiteam.eu/wp-content/uploads/2021/05/lotos-04b.jpg", "https://topauto.co.za/wp-content/uploads/2025/02/The-Pantry-petrol-station-5.jpg"],
        "category": "business"
    },
    {
        "id": 7000932,
        "adres": "Warsaw, Ursynow",
        "price": 975,
        "currency": "EUR",
        "details": "2-room apartment (open kitchen)",
        "size": 50,
        "added": "2025-04-10",
        "saved": 0,
        "status": "available",
        "image": ['https://fancyhouse-design.com/wp-content/uploads/2023/11/Contemporary-interior-decorations-breathe-life-into-this-penthouse-living-rooms-design..jpg', 'https://fancyhouse-design.com/wp-content/uploads/2023/11/An-inviting-L-shaped-sofa-anchors-this-penthouses-spacious-living-room-layout..jpg'],
        "category": "living"
    },
    {
        "id": 7000933,
        "adres": "Warsaw, Wawer",
        "price": 1550,
        "currency": "USD",
        "details": "Shop (80 sq.m.) for rent in Shopping Mall",
        "size": 80,
        "added": "2025-03-19",
        "saved": 1,
        "status": "available",
        "image": ['https://retailminded.com/wp-content/uploads/2023/12/Optimized-clark-street-mercantile-P3pI6xzovu0-unsplash.jpg'],
        "category": "business"
    },
    {
        "id": 7000934,
        "adres": "Warsaw, Praga PLN",
        "price": 1020,
        "currency": "EUR",
        "details": "2-room apartment with cosy kitchen",
        "size": 49,
        "added": "2025-04-10",
        "saved": 1,
        "status": "reserved",
        "image": ["https://www.decorilla.com/online-decorating/wp-content/uploads/2020/08/mid-century-modern-apartment-decor.jpg"],
        "category": "living"
    },
    {
        "id": 7000935,
        "adres": "London, Kingston",
        "price": 715,
        "currency": "EUR",
        "details": "1-room apartment",
        "size": 38,
        "added": "2025-02-19",
        "saved": 0,
        "status": "available",
        "image": ['https://st.hzcdn.com/simgs/69c1522e0fdafc56_4-7785/home-design.jpg', 'https://st.hzcdn.com/simgs/pictures/living-rooms/ultra-modern-apartment-design-and-construction-hometek-renovations-and-extensions-img~22e107bf0fdafc66_4-7786-1-3b261a6.jpg', 'https://st.hzcdn.com/simgs/f31128660fdafc62_4-2742/home-design.jpg'],
        "category": "living"
    },
    {
        "id": 7000936,
        "adres": "Warsaw, Ursynow",
        "price": 1900,
        "currency": "USD",
        "details": "Pharmacy",
        "size": 65,
        "added": "2025-01-31",
        "saved": 0,
        "status": "available",
        "image": ["https://visionshopfitters.co.uk/wp-content/uploads/2019/11/Mansons-Pharmacy-Shopfront-1800x1200.jpg", "https://antdisplay.com/pub/media/furniture/022e9691c5ba65d23cbf27a53f83163e.jpg"],
        "category": "business"
    },
    {
        "id": 7000937,
        "adres": "London, Center",
        "price": 1200,
        "currency": "USD",
        "details": "2-room apartment with cosy kitchen",
        "size": 57,
        "added": "2025-03-10",
        "saved": 0,
        "status": "reserved",
        "image": ['https://www.caffelattehome.com/img/press/new-thumbnails/modern-flat-with-a-striking-texture.jpg'],
        "category": "living"
    },
    {
        "id": 7000938,
        "adres": "London, Downtown",
        "price": 1200,
        "currency": "USD",
        "details": "2-room apartment with cosy kitchen",
        "size": 57,
        "added": "2025-03-03",
        "saved": 0,
        "status": "available",
        "image": ['https://media.designcafe.com/wp-content/uploads/2019/12/17054254/modern-classic-furniture-for-apartment.jpg', 'https://media.designcafe.com/wp-content/uploads/2019/12/17054255/urban-modern-style-kitchen-design-for-apartment.jpg', 'https://media.designcafe.com/wp-content/uploads/2019/12/17054248/eclectic-style-apartment-interior-design.jpg'],
        "category": "living"
    },
    {
        "id": 7000939,
        "adres": "Warsaw, Mokotow",
        "price": 1075,
        "currency": "USD",
        "details": "2-room apartment with terrace",
        "size": 48,
        "added": "2025-04-17",
        "saved": 0,
        "status": "available",
        "image": ['https://media.designcafe.com/wp-content/uploads/2019/12/17054310/comfortable-cosy-materials-fireplace.jpg', 'https://media.designcafe.com/wp-content/uploads/2019/12/17054313/dress-up-the-exteriors.jpg', 'https://media.designcafe.com/wp-content/uploads/2019/12/17054318/relaxed-and-casual-appeal.jpg'],
        "category": "living"
    },
    {
        "id": 7000940,
        "adres": "Warsaw, Mokotow",
        "price": 1900,
        "currency": "EUR",
        "details": "250 sq.m. office space",
        "size": 250,
        "added": "2025-02-10",
        "saved": 0,
        "status": "reserved",
        "image": ['https://www.ceioffice.com/wp-content/uploads/office-space-design.jpg'],
        "category": "business"
    },
    {
        "id": 7000941,
        "adres": "Warsaw, Praga PLN",
        "price": 1020,
        "currency": "USD",
        "details": "2-room apartment with open kitchen",
        "size": 50,
        "added": "2025-04-22",
        "saved": 0,
        "status": "available",
        "image": ['https://media.designcafe.com/wp-content/uploads/2019/12/17054314/large-kitchens-dining.jpg', 'https://media.designcafe.com/wp-content/uploads/2019/12/17054301/large-furnitures-that-multitask.jpg', 'https://i.etsystatic.com/41193567/r/il/2672de/5684778253/il_570xN.5684778253_3u6z.jpg'],
        "category": "living"
    },
    {
        "id": 7000942,
        "adres": "London, Bexley",
        "price": 1715,
        "currency": "EUR",
        "details": "2-level apartment",
        "size": 130,
        "added": "2025-03-19",
        "saved": 1,
        "status": "available",
        "image": ['https://media.designcafe.com/wp-content/uploads/2019/12/17054302/LARGE-WINDOWS-AND-DOORS.jpg', 'https://media.designcafe.com/wp-content/uploads/2019/12/17054309/VIBRANT-FURNISHINGS-AND-ACCESSORIES.jpg', 'https://uniquehomes.bg/wp-content/uploads/2018/01/beautiful-modern-apartment-exterior-apartment-exterior-design-ideas-philippines-apartment-exterior-design-ideas-1024x714.jpg'],
        "category": "living"
    },
    {
        "id": 7000943,
        "adres": "Warsaw, Ursynow",
        "price": 975,
        "currency": "USD",
        "details": "2-room apartment (open kitchen)",
        "size": 60,
        "added": "2025-04-21",
        "saved": 1,
        "status": "available",
        "image": ['https://www.decorilla.com/online-decorating/wp-content/uploads/2020/08/mid-century-modern-apartment-decor.jpg', 'https://media.designcafe.com/wp-content/uploads/2019/12/17054256/CRAFTING-LOUNGING-SPACES.jpg'],
        "category": "living"
    },
    {
        "id": 7000944,
        "adres": "Warsaw, Mokotow",
        "price": 1615,
        "currency": "EUR",
        "details": "3-room PREMIUM apartment",
        "size": 78,
        "added": "2025-04-10",
        "saved": 0,
        "status": "reserved",
        "image": ['https://www.decorilla.com/online-decorating/wp-content/uploads/2018/03/feature.jpg'],
        "category": "living"
    },
    {
        "id": 7000945,
        "adres": "Kyiv, Center",
        "price": 1775,
        "currency": "USD",
        "details": "220 sq.m. office space",
        "size": 220,
        "added": "2025-03-15",
        "saved": 0,
        "status": "available",
        "image": ['https://www.mitie.com/wp-content/uploads/2022/09/Modern-office-workspace-with-different-areas-for-employees.jpg', 'https://static.skepp.com/public/cache/cover_s3/images/uploads/blog/overzichtsfoto-urban-min-1-2002.jpg', 'https://i.pinimg.com/736x/f9/40/f7/f940f756980330513e2907decd5dd4f0.jpg'],
        "category": "business"
    },
    {
        "id": 7000946,
        "adres": "Warsaw, Praga PLN",
        "price": 2410,
        "currency": "EUR",
        "details": "Ready fashion store, 115 sq.m.",
        "size": 115,
        "added": "2025-02-19",
        "saved": 0,
        "status": "reserved",
        "image": ['https://i.pinimg.com/736x/58/92/98/58929859c6f1c61ccf9f42299dbc0c43.jpg'],
        "category": "business"
    }
]

export default aparts;